default:
  timeout: 60
  frequency: 5
  endpoint: http://ec2-54-162-62-231.compute-1.amazonaws.com/register
users:
  timeout: 60
  frequency: 5
  endpoint: http://ec2-54-162-62-231.compute-1.amazonaws.com/register